font_family       FiraCode Nerd Font
font_size         9
enable_audio_bell no
# shell             tmux
#include ./kitty_tokyonight_night.conf
# include ./tokyo_night_night.conf

modify_font underline_position 2
modify_font underline_thickness 175%


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
